/**
 * Better Auth's tables, exactly as its Kysely adapter expects them: camelCase
 * column names (quoted), text ids we generate as UUIDs (`generateId: 'uuid'`
 * in packages/identity/src/auth.ts), and `timestamptz` for every date.
 *
 * Written by hand rather than generated by `@better-auth/cli migrate` so the
 * schema lives in the same numbered ledger as everything else and never
 * depends on a CLI whose version drifts from the library's. When Better Auth
 * adds a column, the change is a new migration here.
 *
 * The passkey table is the `@better-auth/passkey` plugin's.
 */

import { type Kysely, sql } from 'kysely';

export async function up(db: Kysely<unknown>): Promise<void> {
  await db.schema
    .createTable('user')
    .addColumn('id', 'uuid', (col) => col.primaryKey())
    .addColumn('name', 'text', (col) => col.notNull())
    .addColumn('email', 'text', (col) => col.notNull().unique())
    .addColumn('emailVerified', 'boolean', (col) => col.notNull().defaultTo(false))
    .addColumn('image', 'text')
    .addColumn('createdAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('updatedAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .execute();

  await db.schema
    .createTable('session')
    .addColumn('id', 'uuid', (col) => col.primaryKey())
    .addColumn('expiresAt', 'timestamptz', (col) => col.notNull())
    .addColumn('token', 'text', (col) => col.notNull().unique())
    .addColumn('createdAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('updatedAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('ipAddress', 'text')
    .addColumn('userAgent', 'text')
    .addColumn('userId', 'uuid', (col) => col.notNull().references('user.id').onDelete('cascade'))
    .execute();
  await db.schema.createIndex('session_userId_idx').on('session').column('userId').execute();

  await db.schema
    .createTable('account')
    .addColumn('id', 'uuid', (col) => col.primaryKey())
    .addColumn('accountId', 'text', (col) => col.notNull())
    .addColumn('providerId', 'text', (col) => col.notNull())
    .addColumn('userId', 'uuid', (col) => col.notNull().references('user.id').onDelete('cascade'))
    .addColumn('accessToken', 'text')
    .addColumn('refreshToken', 'text')
    .addColumn('idToken', 'text')
    .addColumn('accessTokenExpiresAt', 'timestamptz')
    .addColumn('refreshTokenExpiresAt', 'timestamptz')
    .addColumn('scope', 'text')
    .addColumn('password', 'text')
    .addColumn('createdAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('updatedAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    // One provider identity belongs to one account — the linking policy's
    // ALREADY_LINKED is this constraint surfacing as a value.
    .addUniqueConstraint('account_provider_account_unique', ['providerId', 'accountId'])
    .execute();
  await db.schema.createIndex('account_userId_idx').on('account').column('userId').execute();

  await db.schema
    .createTable('verification')
    .addColumn('id', 'uuid', (col) => col.primaryKey())
    .addColumn('identifier', 'text', (col) => col.notNull())
    .addColumn('value', 'text', (col) => col.notNull())
    .addColumn('expiresAt', 'timestamptz', (col) => col.notNull())
    .addColumn('createdAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .addColumn('updatedAt', 'timestamptz', (col) => col.notNull().defaultTo(sql`now()`))
    .execute();
  await db.schema
    .createIndex('verification_identifier_idx')
    .on('verification')
    .column('identifier')
    .execute();

  await db.schema
    .createTable('passkey')
    .addColumn('id', 'uuid', (col) => col.primaryKey())
    .addColumn('name', 'text')
    .addColumn('publicKey', 'text', (col) => col.notNull())
    .addColumn('userId', 'uuid', (col) => col.notNull().references('user.id').onDelete('cascade'))
    .addColumn('credentialID', 'text', (col) => col.notNull())
    .addColumn('counter', 'integer', (col) => col.notNull())
    .addColumn('deviceType', 'text', (col) => col.notNull())
    .addColumn('backedUp', 'boolean', (col) => col.notNull())
    .addColumn('transports', 'text')
    .addColumn('createdAt', 'timestamptz', (col) => col.defaultTo(sql`now()`))
    .addColumn('aaguid', 'text')
    .execute();
  await db.schema.createIndex('passkey_userId_idx').on('passkey').column('userId').execute();
  await db.schema
    .createIndex('passkey_credentialID_idx')
    .on('passkey')
    .column('credentialID')
    .execute();
}

export async function down(db: Kysely<unknown>): Promise<void> {
  await db.schema.dropTable('passkey').execute();
  await db.schema.dropTable('verification').execute();
  await db.schema.dropTable('account').execute();
  await db.schema.dropTable('session').execute();
  await db.schema.dropTable('user').execute();
}
