import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import safeFunctions from '@campfhir/safe-functions';
import logTemplateFields from './scripts/eslint-rules/log-template-fields.js';

/**
 * The safe-coding harness. Everything below the framework boundary must
 * return a `Result`; nothing may throw; every `Result` must be handled; every
 * error tag must be a string literal. The rules are type-aware, so they run
 * with `projectService` and only over files a tsconfig covers.
 *
 * Three tiers, by file pattern:
 *
 * 1. Code we own the signatures of (packages/*\/src, apps/voice-gateway/src,
 *    apps/web/lib): the full strict set.
 * 2. Files where a framework dictates the signature (Next route handlers,
 *    pages, layouts, server actions; MCP tool handlers, whose SDK expects a
 *    plain promise): `no-unwrapped-async` is off. `no-throw` and
 *    `require-result-handling` still apply — they catch the call INTO a
 *    throwing function, which is where the fix belongs.
 * 3. Tests and testing helpers: async callbacks handed to `it()` can never be
 *    an `AsyncResult`, so `no-unwrapped-async` and `require-tagged-errors`
 *    are off. `no-throw` and `require-result-handling` stay on: a test that
 *    drops a Result on the floor is not testing what it claims to.
 *
 * `plugins: { result: safeFunctions }` is used throughout rather than the
 * shipped presets. Mixing the two on overlapping globs makes ESLint refuse to
 * start ("Cannot redefine plugin result") — see the plugin's README.
 */

const TEST_FILES = [
  '**/*.test.ts',
  '**/*.test.tsx',
  '**/*.integration.test.ts',
  '**/testing.ts',
  '**/testing/**/*.ts',
  'packages/testing/src/**/*.ts',
  'apps/web/e2e/**/*.ts',
];

const FRAMEWORK_OWNED = [
  'apps/web/app/**/*.ts',
  'apps/web/app/**/*.tsx',
  'apps/web/components/**/*.tsx',
  'apps/web/lib/mcp/**/*.ts',
  'apps/web/instrumentation.ts',
  'apps/web/proxy.ts',
  'packages/mcp-tools/src/**/*.ts',
  'packages/db/scripts/**/*.ts',
  // Kysely runs a migration's up/down as Promise<void>; the runner wraps them.
  'packages/db/src/migrations/[0-9][0-9][0-9]-*.ts',
  // The seed helper is called only from those migrations and shares their signature.
  'packages/db/src/migrations/seed.ts',
];

export default [
  {
    ignores: [
      '**/.next/**',
      '**/dist/**',
      '**/node_modules/**',
      '**/coverage/**',
      '.claude/worktrees/**',
      '**/*.config.js',
      '**/*.config.mjs',
      '**/*.config.ts',
      // The local ESLint rules themselves — plain ESM consumed by this
      // config, outside every tsconfig project.
      'scripts/eslint-rules/**',
      // Build script for the migrate image; runs under node directly.
      'packages/db/scripts/build-migrations.js',
      // Generated by kysely-codegen; regenerate, never edit or lint.
      'packages/db/src/db.types.ts',
      // Next writes these; they are not ours.
      'apps/web/next-env.d.ts',
      // Deliberately broken code that packages/core/src/harness.test.ts lints
      // itself (with ignore: false) to prove the rules below still fire.
      'packages/core/src/harness-fixtures/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      result: safeFunctions,
      // Local rules live in scripts/eslint-rules. See that file for why a
      // type cannot catch what it catches.
      'glib-glub': { rules: { 'log-template-fields': logTemplateFields } },
    },
    rules: {
      // invariant.ts is the one file allowed to throw: a programmer error has
      // no caller that can act on it. See that file.
      'result/no-throw': ['error', { allow: ['packages/core/src/invariant.ts'] }],
      'result/no-unwrapped-async': 'error',
      'result/require-result-handling': 'error',
      'result/require-tagged-errors': 'error',
      // `application`, `version` and `commit` are handed to createLogger as
      // global attributes in each app's logger, so they resolve on every
      // record without a call site repeating them.
      'glib-glub/log-template-fields': [
        'error',
        { globalAttributes: ['application', 'version', 'commit'] },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      // No `as` casts. A cast is a promise the compiler cannot check; the
      // rare justified one carries an eslint-disable with its reason.
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        {
          assertionStyle: 'never',
        },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    files: FRAMEWORK_OWNED,
    rules: {
      'result/no-unwrapped-async': 'off',
    },
  },
  {
    files: TEST_FILES,
    rules: {
      'result/no-unwrapped-async': 'off',
      'result/require-tagged-errors': 'off',
    },
  },
];
