/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface AssessmentQuestions {
  assessment_id: string;
  position: number;
  question_id: string;
}

export interface Assessments {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: string;
  lesson_id: string | null;
  purpose: string;
  status: Generated<string>;
  subject_id: string | null;
  title: string;
  track_id: string | null;
}

export interface Attempts {
  assessment_id: string;
  id: string;
  learner_id: string;
  submitted_at: Timestamp;
}

export interface Cards {
  back: string;
  deck_id: string;
  due_at: Generated<Timestamp>;
  easiness: Generated<Numeric>;
  front: string;
  id: string;
  interval_days: Generated<number>;
  last_reviewed_at: Timestamp | null;
  repetitions: Generated<number>;
}

export interface Categories {
  id: string;
  name: string;
  slug: string;
}

export interface Decks {
  created_at: Generated<Timestamp>;
  id: string;
  learner_id: string;
  lesson_id: string | null;
  title: string;
}

export interface Enrollments {
  enrolled_at: Generated<Timestamp>;
  id: string;
  learner_id: string;
  status: Generated<string>;
  track_id: string;
}

export interface Gradings {
  feedback: Generated<string>;
  graded_at: Timestamp;
  graded_by: string | null;
  grader: string;
  id: string;
  override_of: string | null;
  response_id: string;
  score: Numeric;
}

export interface Guardianships {
  accepted_at: Timestamp | null;
  guardian_id: string;
  invited_at: Generated<Timestamp>;
  learner_id: string;
  status: string;
}

export interface LearnerProfiles {
  about: Generated<string>;
  grade_label: string | null;
  interests: Generated<string[]>;
  learning_styles: Generated<string[]>;
  preferred_language: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface LearnerSettings {
  age_band: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface LearningObjectives {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: string;
  learner_id: string;
  set_by: string;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface LessonProgress {
  completed_at: Generated<Timestamp>;
  enrollment_id: string;
  lesson_id: string;
}

export interface Lessons {
  content: Generated<string>;
  estimated_minutes: Generated<number>;
  id: string;
  objectives: Generated<string[]>;
  position: number;
  title: string;
  unit_id: string;
}

export interface LevelEstimates {
  attempt_id: string;
  estimated_at: Timestamp;
  learner_id: string;
  level: string;
  score: Numeric;
  subject_id: string;
}

export interface PacingPlans {
  cadence: string;
  enrollment_id: string;
  sessions_per_period: number;
  started_at: Timestamp;
}

export interface Passkey {
  aaguid: string | null;
  backedUp: boolean;
  counter: number;
  createdAt: Generated<Timestamp | null>;
  credentialID: string;
  deviceType: string;
  id: string;
  name: string | null;
  publicKey: string;
  transports: string | null;
  userId: string;
}

export interface PersonalisationSnapshots {
  built_at: Generated<Timestamp>;
  content: Json;
  digest: string;
  learner_id: string;
  version: number;
}

export interface Questions {
  body: Json;
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  points: Generated<number>;
  prompt: string;
}

export interface Responses {
  answer: Json | null;
  attempt_id: string;
  id: string;
  question_id: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface Subjects {
  category_id: string;
  id: string;
  name: string;
  slug: string;
}

export interface Tracks {
  authored_by: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  language: Generated<string>;
  level_max: string;
  level_min: string;
  origin: string;
  pedagogy: Generated<string>;
  subject_id: string;
  summary: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
  visibility: Generated<string>;
}

export interface Units {
  id: string;
  position: number;
  title: string;
  track_id: string;
}

export interface UploadExtractions {
  extracted_at: Generated<Timestamp>;
  summary: string;
  tags: Generated<string[]>;
  text: string;
  upload_id: string;
}

export interface Uploads {
  blob_key: string;
  byte_size: number;
  created_at: Generated<Timestamp>;
  file_name: string;
  id: string;
  learner_id: string;
  mime_type: string;
  rejection_reason: string | null;
  status: Generated<string>;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  role: string;
  user_id: string;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  assessment_questions: AssessmentQuestions;
  assessments: Assessments;
  attempts: Attempts;
  cards: Cards;
  categories: Categories;
  decks: Decks;
  enrollments: Enrollments;
  gradings: Gradings;
  guardianships: Guardianships;
  learner_profiles: LearnerProfiles;
  learner_settings: LearnerSettings;
  learning_objectives: LearningObjectives;
  lesson_progress: LessonProgress;
  lessons: Lessons;
  level_estimates: LevelEstimates;
  pacing_plans: PacingPlans;
  passkey: Passkey;
  personalisation_snapshots: PersonalisationSnapshots;
  questions: Questions;
  responses: Responses;
  session: Session;
  subjects: Subjects;
  tracks: Tracks;
  units: Units;
  upload_extractions: UploadExtractions;
  uploads: Uploads;
  user: User;
  user_roles: UserRoles;
  verification: Verification;
}
