/**
 * Generated by kysely-codegen — do not edit. Regenerate after adding a
 * migration:
 *
 *   DATABASE_URL=… pnpm --filter @glib-glub/db db:types
 */

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface DB {}
